### ISSUE TITLE
[Feature Request] Add AcceptHeader and a ContentType in DownstreamApiOptions 

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-abstractions-for-dotnet#123]
**Is your feature request related to a problem? Please describe.**
We can do better for the serialization

**Describe the solution you'd like**
Add 2 string properties AcceptHeader and a ContentType in DownstreamApiOptions

**Comment by jennyf19** [comment]
> **Is your feature request related to a problem? Please describe.** We can do better for the serialization
> 
> **Describe the solution you'd like** Add 2 string properties AcceptHeader and a ContentType in DownstreamApiOptions

ContentType would be in the response, in Id Web, not here.

**Comment by jmprieur** [comment]
Released in 5.3.0

**Comment by jmprieur** [comment]
Done
