### ISSUE TITLE
[Feature Request] Microsoft.Identity.Abstractions should bring a net462 target framework

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-abstractions-for-dotnet#45]
**Is your feature request related to a problem? Please describe.**
When net462 libraries (think Id.Web, SAL) take a dependency on netstandard2.0 libraries, this ends-up pulling the whole framework, whereas Microsoft.Identity.Abstractions  is tiny and does not reference much. By adding direct support for net462, this enables to draw less dependencies

**Describe the solution you'd like**
Add the net462 target framework

**Describe alternatives you've considered**
None

**Additional context**
See also the common dependency management.

**Comment by jennyf19** [comment]
in 1.0.6-preview
