### ISSUE TITLE
[Feature Request] Replace 'JwtClaim' with 'PopClaim' on AquireTokenOptions

### ISSUE THREAD

**Issue by sruke** [AzureAD/microsoft-identity-abstractions-for-dotnet#74]
**Is your feature request related to a problem? Please describe.**
Property name JwtClaim is specific to Json Web Tokens (JWT). 

**Describe the solution you'd like**
The intent of the claim is providing proof-of-possession. By renaming the property to PopClaim, it can also be applied to other token types.

**Comment by jennyf19** [comment]
In 3.0.1 release
