### ISSUE TITLE
[Documentation] Release notes for 3.x releases

### ISSUE THREAD

**Issue by tomkerkhove** [AzureAD/microsoft-identity-abstractions-for-dotnet#89]
### Documentation related to component

General

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

New 3.x releases are created but it's hard to understand what breaking changes it include and how to migrate.

Additionally, no new GitHub releases are created after 2.1.0

**Comment by jennyf19** [comment]
will fix. Thanks @tomkerkhove

**Comment by jennyf19** [comment]
The changelog.md was update to date. Have added the releases in GitHub.
