### ISSUE TITLE
[Feature Request] add ability to build and create packages locally

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/microsoft-identity-abstractions-for-dotnet#9]
It would be nice to have a simple way to build and produce packages from the command line.

**Comment by brentschmaltz** [comment]
@jmprieur yes, to build packages this will work.
A build script can do more such as:
Backcompat testing
Setting up and cleaning out bin/obj/artifacts folders
Set unique version for packages
Analyze log messages for unused or duplicates
Run tests (all or specific)

**Comment by jmprieur** [comment]
Thanks for explaining, @brentschmaltz
I think we should do that using MSBuild rules (generalized to all libraries). The point is MSBUILD knows where the source / project / artefacts are. 

dotnet test runs the tests.

**Comment by brentschmaltz** [comment]
@jmprieur if we can use MSBuild rules, that would be great.
Can we scope running tests to a subset?

On a separate topic, what test runner do you want to use?

**Comment by jmprieur** [comment]
@brentschmaltz 
- `dotnet test` has very powerful options, including filtering of the tests to run. See [Run selected unit tests](https://learn.microsoft.com/dotnet/core/testing/selective-unit-tests?pivots=mstest)
